#!/usr/bin/env bash

# Help
if [ $# -eq 0 ]
then
    echo "USAGE: $(basename $0) APPNAME [ARGS]";
    echo "To list available tools: $(basename $0) list";
    exit
fi

# Get the root directory in case this script is being called from elsewhere
#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# Employ this version if you have created a symbolic link to this file  - DCK
DIR="$( cd "$( dirname  "$(readlink -f ${BASH_SOURCE[0]} )" )" && pwd )"

# List the available tools (this is a little hacky)
if [ "$1" = "list" ]
then
  for d in `ls $DIR/src/edu/unc/genomics`
  do
    if [ -d $DIR/src/edu/unc/genomics/$d ]
    then
      for f in `ls $DIR/src/edu/unc/genomics/$d/*`
      do
        scriptname=`basename $f .java`
        echo $d.$scriptname
      done
    fi
  done
  exit
fi

# Run a tool with the passed arguments
java -Xmx2000m -Dlog4j.configuration=log4j.properties -cp $DIR:$DIR/build:$DIR/dist/*:$DIR/lib/* edu.unc.genomics."$@"
