---
title: "read subsampling with basewise comparison (fraction of bases recovered)"
author: "Deekrob"
date: "10/9/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r }

##        ##
##        ##
##   LE   ##
##        ##
##        ##

read.table(textConnection("
2 740236
2.5 977060
3 1123253
3.5 1254791
4 1380973
4.5 1520174
5 1737007
5.5 1819799
6 2008815
6.5 2129393 
 8.799602  3285607 
   ")) -> LE.df
colnames(LE.df) <- c("depth_millions","bases_recovered")
LE.df$bases_recovered = LE.df$bases_recovered/max(LE.df$bases_recovered)
# fit exponential model
# initial parameters
theta.0 <- max(LE.df$bases_recovered) * 1.1
model.0 <- lm(log(- bases_recovered + theta.0) ~ depth_millions, data=LE.df)
alpha.0 <- -exp(coef(model.0)[1])
beta.0 <- coef(model.0)[2]
start <- list(alpha = alpha.0, beta = beta.0, theta = theta.0)
model <- nls(bases_recovered ~ alpha * exp(beta * depth_millions) + theta , data = LE.df, start = start)
summary(model)
fitted_alpha = coef(model)['alpha']
fitted_beta = coef(model)['beta']
fitted_theta = coef(model)['theta']
theoretical_95 = .95 * fitted_theta
sequencing_depth_for_95 = log((theoretical_95-fitted_theta)/fitted_alpha)/fitted_beta



plot(LE.df$depth_millions, LE.df$bases_recovered,main="LE Sequencing Depth Saturation Curve", ylim=c(0,6800),xlim=c(1,10),xlab="Millions of reads aligned",ylab="Reproducible Peaks Called")
lines(seq(1,12,by=.5), predict(model, list(depth_millions= seq(1,12,by=.5))), col = 'skyblue', lwd = 3)
abline(h=coef(model)['theta'], lty=3, col='grey')
points(LE.df[11,],pch="x")
text(5,1250, pos=4,
  sprintf("observed called peaks: %d\n %.1f%% of theoretical maximum",
          LE.df[11,2], 
          100* LE.df[11,2]/coef(model)['theta']),
  cex=.9
)
points(4.8,1300,pch="x")
points(4.8,1300)

points(4.8,600)
text(5,500, pos=4, sprintf("peak calling/IDR after \nsubsampling"),cex=.9)


##        ##
##        ##
##   L1   ##
##        ##
##        ##
(L1.df=data.frame( depth_millions=c(seq(2,6.5,by=.5),7.081766), bases_recovered=c(899346,964786,1111175,1118014,1182615,1281784,1288691,1338139,1383979,1462601,1613365)))

# fit exponential model
# initial parameters
theta.0 <- max(L1.df$bases_recovered) * 1.1
model.0 <- lm(log(- bases_recovered + theta.0) ~ depth_millions, data=L1.df)
alpha.0 <- -exp(coef(model.0)[1])
beta.0 <- coef(model.0)[2]
start <- list(alpha = alpha.0, beta = beta.0, theta = theta.0)
model <- nls(bases_recovered ~ alpha * exp(beta * depth_millions) + theta , data = L1.df, start = start)
summary(model)


plot(L1.df$depth_millions, L1.df$bases_recovered,main="L1 Sequencing Depth Saturation Curve", ylim=c(0,3000),xlim=c(1,10),xlab="Millions of reads aligned",ylab="Reproducible Peaks Called")
lines(seq(1,12,by=.5), predict(model, list(depth_millions= seq(1,12,by=.5))), col = 'skyblue', lwd = 3)
abline(h=coef(model)['theta'], lty=3, col='grey')
points(L1.df[11,],pch="x")
text(5,1250, pos=4,
  sprintf("observed called peaks: %d\n %.1f%% of theoretical maximum",
          L1.df[11,2], 
          100* L1.df[11,2]/coef(model)['theta']),
  cex=.9
)
points(4.8,1300,pch="x")
points(4.8,1300)

points(4.8,600)
text(5,500, pos=4, sprintf("peak calling/IDR after \nsubsampling"),cex=.9)


##        ##
##        ##
##   L3   ##
##        ##
##        ##

read.table(textConnection("
2 4007384
2.5 4249964
3 4615773
3.5 4839423
4 5133378
4.5 5377778
5 5668986
5.5 5898912
6 6137086
6.5 6690245
6.780756 7208770
  ")) -> L3.df
colnames(L3.df) <- c("depth_millions","bases_recovered")

 # fit exponential model
# initial parameters
theta.0 <- max(L3.df$bases_recovered) * 1.1
model.0 <- lm(log(- bases_recovered + theta.0) ~ depth_millions, data=L3.df)
alpha.0 <- -exp(coef(model.0)[1])
beta.0 <- coef(model.0)[2]
start <- list(alpha = alpha.0, beta = beta.0, theta = theta.0)
model <- nls(bases_recovered ~ alpha * exp(beta * depth_millions) + theta , data = L3.df, start = start)
summary(model)


plot(L3.df$depth_millions, L3.df$bases_recovered,main="L3 Sequencing Depth Saturation Curve", ylim=c(0,11000),xlim=c(1,10),xlab="Millions of reads aligned",ylab="Reproducible Peaks Called")
lines(seq(1,12,by=.5), predict(model, list(depth_millions= seq(1,12,by=.5))), col = 'skyblue', lwd = 3)
abline(h=coef(model)['theta'], lty=3, col='grey')
points(L3.df[11,],pch="x")
text(5,3500, pos=4,
  sprintf("observed called peaks: %d\n %.1f%% of theoretical maximum",
          L3.df[11,2], 
          100* L3.df[11,2]/coef(model)['theta']),
  cex=.9
)
points(4.8,4000,pch="x")
points(4.8,4000)

points(4.8,2000)
text(5,2100, pos=4, sprintf("peak calling/IDR after \nsubsampling"),cex=.9)
```

